import os
import sys
import pprint
import json
import concurrent.futures

# Add parent dir to path so we can import from evaluation
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from belief_store.llm_client import OllamaClient

# Import the original scenario variables
from evaluation.scenario_sets.extended.loan import LOAN_BELIEF_MAINTENANCE_TURNS
from evaluation.scenario_sets.extended.alien_clinic import ALIEN_BELIEF_MAINTENANCE_TURNS
from evaluation.scenario_sets.extended.crime_scene import CRIME_BELIEF_MAINTENANCE_TURNS
from evaluation.scenario_sets.extended.thorncrester import THORNCRESTER_BELIEF_MAINTENANCE_TURNS

from evaluation.scenario_sets.belief_awareness import (
    LOAN_ABSURD_TURNS, LOAN_ABSURD_TEMPORAL_TURNS, LOAN_GROUNDING_TURNS,
    ALIEN_ABSURD_TURNS, ALIEN_ABSURD_TEMPORAL_TURNS, ALIEN_GROUNDING_TURNS,
    CRIME_ABSURD_TURNS, CRIME_ABSURD_TEMPORAL_TURNS, CRIME_GROUNDING_TURNS,
    THORNCRESTER_ABSURD_TURNS, THORNCRESTER_ABSURD_TEMPORAL_TURNS, THORNCRESTER_GROUNDING_TURNS
)

from evaluation.scenario_sets.hard import (
    LOAN_HARD_TURNS, ALIEN_HARD_TURNS, CRIME_HARD_TURNS, THORNCRESTER_HARD_TURNS
)

from evaluation.scenario_sets.noise import (
    ALIEN_ABSURD_TEMPORAL_NOISE_TURNS,
    CRIME_ABSURD_TEMPORAL_NOISE_TURNS,
    LOAN_ABSURD_TEMPORAL_NOISE_TURNS,
    THORNCRESTER_ABSURD_TEMPORAL_NOISE_TURNS,
)

USE_NOISE_ONLY = True
NOISE_OUTPUT_SUFFIX = "_noise"

# Mapping domains to their respective subsets
TARGETS = {
    "LOAN": {
        "BELIEF_MAINTENANCE": LOAN_BELIEF_MAINTENANCE_TURNS,
        "ABSURD": LOAN_ABSURD_TURNS,
        "ABSURD_TEMPORAL": LOAN_ABSURD_TEMPORAL_TURNS,
        "GROUNDING": LOAN_GROUNDING_TURNS,
        "HARD": LOAN_HARD_TURNS,
    },
    "ALIEN": {
        "BELIEF_MAINTENANCE": ALIEN_BELIEF_MAINTENANCE_TURNS,
        "ABSURD": ALIEN_ABSURD_TURNS,
        "ABSURD_TEMPORAL": ALIEN_ABSURD_TEMPORAL_TURNS,
        "GROUNDING": ALIEN_GROUNDING_TURNS,
        "HARD": ALIEN_HARD_TURNS,
    },
    "CRIME": {
        "BELIEF_MAINTENANCE": CRIME_BELIEF_MAINTENANCE_TURNS,
        "ABSURD": CRIME_ABSURD_TURNS,
        "ABSURD_TEMPORAL": CRIME_ABSURD_TEMPORAL_TURNS,
        "GROUNDING": CRIME_GROUNDING_TURNS,
        "HARD": CRIME_HARD_TURNS,
    },
    "THORNCRESTER": {
        "BELIEF_MAINTENANCE": THORNCRESTER_BELIEF_MAINTENANCE_TURNS,
        "ABSURD": THORNCRESTER_ABSURD_TURNS,
        "ABSURD_TEMPORAL": THORNCRESTER_ABSURD_TEMPORAL_TURNS,
        "GROUNDING": THORNCRESTER_GROUNDING_TURNS,
        "HARD": THORNCRESTER_HARD_TURNS,
    }
}

if USE_NOISE_ONLY:
    TARGETS = {
        "LOAN": {
            "ABSURD_TEMPORAL_NOISE": LOAN_ABSURD_TEMPORAL_NOISE_TURNS,
        },
        "ALIEN": {
            "ABSURD_TEMPORAL_NOISE": ALIEN_ABSURD_TEMPORAL_NOISE_TURNS,
        },
        "CRIME": {
            "ABSURD_TEMPORAL_NOISE": CRIME_ABSURD_TEMPORAL_NOISE_TURNS,
        },
        "THORNCRESTER": {
            "ABSURD_TEMPORAL_NOISE": THORNCRESTER_ABSURD_TEMPORAL_NOISE_TURNS,
        },
    }

def format_turn(turn, new_question):
    """Formats a single dictionary turn back into a python string representation."""
    t_copy = turn.copy()
    t_copy["question"] = new_question
    return pprint.pformat(t_copy, indent=4, sort_dicts=False)

def process_domain(domain, subsets, out_dir):
    print(f"\\n[START] Processing Domain: {domain}")
    client = OllamaClient(model="gemma4:e2b", temperature=0.7, num_predict=150)
    
    system_prompt = (
        "You are an expert NLP paraphraser. "
        "Given a question, generate 3 distinct ways to rewrite it while preserving the exact semantic meaning, entities, and logical constraints. "
        "Output ONLY a valid JSON object with a single key 'paraphrases' containing a list of exactly 3 string paraphrases. "
        "Do not include any markdown formatting, just raw JSON. "
        "Example output:\\n"
        '{"paraphrases": ["rewrite 1", "rewrite 2", "rewrite 3"]}'
    )

    suffix = NOISE_OUTPUT_SUFFIX if USE_NOISE_ONLY else ""
    out_filename = f"{domain.lower()}_paraphrased_scenarios{suffix}.py"
    if domain == "ALIEN":
        out_filename = f"alien_clinic_paraphrased_scenarios{suffix}.py"
    elif domain == "CRIME":
        out_filename = f"crime_scene_paraphrased_scenarios{suffix}.py"
        
    out_filepath = os.path.join(out_dir, out_filename)
    
    with open(out_filepath, "w", encoding="utf-8") as f:
        f.write('"""\n')
        f.write(f'Paraphrased Evaluation Scenarios for the {domain} Domain.\n')
        f.write('Generated by scripts/paraphrase_scenarios.py using Ollama gemma3:1b.\n')
        f.write('"""\n\n')
        
        for subset_name, original_turns in subsets.items():
            print(f"[{domain}] Generating paraphrases for subset: {subset_name}")
            
            para_sequences = [[], [], []]
            
            for i, turn in enumerate(original_turns):
                orig_question = turn["question"]
                
                user_prompt = f"Question: {orig_question}"
                response = client.generate(system_prompt=system_prompt, user_prompt=user_prompt, json_mode=True)
                
                try:
                    clean_resp = response.strip()
                    if clean_resp.startswith("```json"):
                        clean_resp = clean_resp[7:]
                    if clean_resp.endswith("```"):
                        clean_resp = clean_resp[:-3]
                        
                    data = json.loads(clean_resp.strip())
                    phrases = data.get("paraphrases", [])
                except Exception as e:
                    print(f"[{domain}] [!] Failed to parse JSON ({e}). Falling back to original.")
                    phrases = []
                    
                # Pad to 3 if we didn't get enough
                while len(phrases) < 3:
                    phrases.append(phrases[0] if phrases else orig_question)
                    
                top_3 = phrases[:3]
                
                for p_idx, para in enumerate(top_3):
                    para_sequences[p_idx].append(format_turn(turn, para))
            
            # Write the 3 sequences to the file
            for p_idx in range(3):
                var_name = f"{domain}_{subset_name}_PARA_{p_idx+1}"
                f.write(f"# {'='*60}\n")
                f.write(f"# PARAPHRASE SET {p_idx+1} for {subset_name}\n")
                f.write(f"# {'='*60}\n")
                f.write(f"{var_name} = [\n")
                
                for i, t_str in enumerate(para_sequences[p_idx]):
                    indented = "    " + t_str.replace("\n", "\n    ")
                    if i < len(para_sequences[p_idx]) - 1:
                        f.write(f"{indented},\n")
                    else:
                        f.write(f"{indented}\n")
                f.write("]\n\n")
    print(f"[DONE] Finished Domain: {domain}")

def main():
    print("Initializing parallel generation with OllamaClient (gemma3:1b)...")
    out_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "evaluation")
    
    # Process all 4 domains concurrently
    with concurrent.futures.ThreadPoolExecutor(max_workers=2) as executor:
        futures = []
        for domain, subsets in TARGETS.items():
            futures.append(executor.submit(process_domain, domain, subsets, out_dir))
            
        for future in concurrent.futures.as_completed(futures):
            try:
                future.result()
            except Exception as e:
                print(f"Error in domain processing: {e}")

if __name__ == "__main__":
    main()
